name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASS}}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./api-produto/src
          file: ./api-produto/src/Dockerfile
          push: true
          tags: |
            vherzog/kubedev-api-produto:latest
            vherzog/kubedev-api-produto:${{github.run_number}}
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v2
      
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
          
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.3
        with:
          image: vherzog/kubedev-api-produto:${{github.run_number}}
          manifests: ./api-produto/deployment.yaml
            
